# Generated by Django 4.2.29 on 2026-03-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_allow_connection_requests_profile_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence & Data Science', 'Artificial Intelligence & Data Science'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence & Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence & Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Electronics Engineering (VLSI Design and Technology)', 'Electronics Engineering (VLSI Design and Technology)'), ('Information Technology', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mechatronics Engineering', 'Mechatronics Engineering'), ('Science & Humanities', 'Science & Humanities')], max_length=150),
        ),
    ]
