# Generated by Django 4.2.29 on 2026-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
