# Generated by Django 4.2.29 on 2026-03-26 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillexchangemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skillexchangesession'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('connect_request', 'Connection Request'), ('connect_accept', 'Connection Accept'), ('skill_exchange', 'Skill Exchange'), ('exchange_message', 'Exchange Message'), ('new_post', 'New Post'), ('org_join', 'Organization Join'), ('org_accept', 'Organization Accept'), ('welcome', 'Welcome')], max_length=20),
        ),
    ]
